### ISSUE TITLE
Externals missing

### ISSUE THREAD

**Issue by limelect** [BeRo1985/pasvulkan#3]
Directory externals is missing  Is EMPTY IN THE ZIP !!!
Clone is OK
Delphi 10.1 errors
[dcc32 Error] PasVulkan.Canvas.pas(3232): E2089 Invalid typecast
More errors
'vulkan-1.dll' missing

**Comment by BeRo1985** [comment]
1. You must either checkout it with GIT with all recursive submodule dependenciesm, or if you're using SVN (like I myself primary) you must do it manually by hand, or download all depended GIT repos (under externals/) manually by hand.
2. And your graphics driver of your graphics card or iGPU should must have installed the vulkan-1.dll (by including the Vulkan runtime and loader stuff from LunarG into the graphics driver setup package) otherwise it seems that your computer doesn't seems to be Vulkan-ready, at least under the Windows operating system.
